"""add_virtual_cards_table

Revision ID: 8421aa8322ba
Revises: c90bd7698c8e
Create Date: 2026-04-08 09:25:32.926023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8421aa8322ba'
down_revision: Union[str, None] = 'c90bd7698c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('card_number_encrypted', sa.Text(), nullable=False),
    sa.Column('card_number_masked', sa.String(length=19), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('cvv_hash', sa.String(length=255), nullable=False),
    sa.Column('cvv_encrypted', sa.Text(), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('daily_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('limit_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('is_online_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_contactless_enabled', sa.Boolean(), nullable=False),
    sa.Column('card_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=30), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_tracking_id', sa.String(length=50), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("card_type IN ('virtual','physical')", name='ck_card_type'),
    sa.CheckConstraint("delivery_status IS NULL OR delivery_status IN ('processing','dispatched','out_for_delivery','delivered')", name='ck_card_delivery_status'),
    sa.CheckConstraint("status IN ('pending_activation','active','frozen','blocked','replaced','expired')", name='ck_card_status'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['virtual_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cards_status', 'virtual_cards', ['status'], unique=False)
    op.create_index('idx_cards_user', 'virtual_cards', ['user_id'], unique=False)
    op.add_column('transactions', sa.Column('card_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('card_last4', sa.String(length=4), nullable=True))
    op.add_column('transactions', sa.Column('merchant_name', sa.String(length=100), nullable=True))
    op.create_index('idx_txn_card', 'transactions', ['card_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'virtual_cards', ['card_id'], ['id'])
    # Update transactions.type CHECK to include card_payment and card_refund
    op.drop_constraint('ck_txn_type', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_txn_type',
        'transactions',
        "type IN ('send','receive','topup','bill','bank_transfer','refund','card_payment','card_refund')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert transactions.type CHECK constraint
    op.drop_constraint('ck_txn_type', 'transactions', type_='check')
    op.create_check_constraint(
        'ck_txn_type',
        'transactions',
        "type IN ('send','receive','topup','bill','bank_transfer','refund')",
    )
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('idx_txn_card', table_name='transactions')
    op.drop_column('transactions', 'merchant_name')
    op.drop_column('transactions', 'card_last4')
    op.drop_column('transactions', 'card_id')
    op.drop_index('idx_cards_user', table_name='virtual_cards')
    op.drop_index('idx_cards_status', table_name='virtual_cards')
    op.drop_table('virtual_cards')
    # ### end Alembic commands ###
